language: python
python:
  - "3.4"
install:
  - pip install requests
  

before_install:
  - pip install codecov
  - pwd
  
  
script:
  - coverage run tests/Snippet_test.py
  - coverage run tests/utils_test.py




after_success:
  - codecov


sudo: required
