language: python
python:
  - "3.4"
install:
  - pip install requests
   - pip install codecov

before_install:
  - pip install codecov
  
  
script:
  - python -m unittest tests/Snippet_test.py
  - python -m unittest tests/utils_test.py




after_success:
  - codecov


sudo: required
